language: android
notifications: 
  slack: plurilock1:9Ddic6DYIACEoXXJyilg07j2
env:
  global:
    - ADB_INSTALL_TIMEOUT=10

android: 
  components:  
  - tools 
  - build-tools-23.0.2 
  - android-23
  - addon-google_apis-google-23
  - extra-android-support
  - extra-google-google_play_services
  - extra-android-m2repository
  - extra-google-m2repository
  - sys-img-armeabi-v7a-android-23

before_script:
  - ./gradlew assembleDebug
  - export ANDROID_HOME=/usr/local/android-sdk
  - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - android list target
  - adb install -r app/build/outputs/apk/app-debug-androidTest-unaligned.apk
  - ./gradlew connectedAndroidTest 
