notifications: 
  slack: plurilock1:9Ddic6DYIACEoXXJyilg07j2

language: android 
android: 
  components:  
  - tools 
  - build-tools-23.0.2 
  - android-23
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-21  

install:
  - sudo apt-get install ruby1.9.1
  - sudo apt-get install ruby1.9.1-dev
  - gem install rspec
  - gem install calabash-android

before_script:
  - ./gradlew assembleDebug
  - export ANDROID_HOME=/usr/local/android-sdk/sources/

script:
  - ./gradlew test
  - calabash-android run ./app/build/outputs/apk/app-debug.apk 
