notifications: 
  slack: plurilock1:9Ddic6DYIACEoXXJyilg07j2

language: android 
android: 
  components:  
  - tools 
  - build-tools-23.0.2 
  - android-23
  - extra-android-m2repository 
script: ./gradlew test
